# Generated by Django 5.2.8 on 2025-11-30 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '20251129072609_alter_candidate_unique_together_and_more'),
        ('organizations', '20251129071919_0001_initial'),
        ('questionbank', '20251130080436_20251129093247_remove_question_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_number_of_questions', models.IntegerField(default=0)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_interview_panels', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panels', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_interview_panels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Panel',
                'verbose_name_plural': 'Interview Panels',
                'db_table': 'interview_panels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPanelCandidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('total_time_taken_in_seconds', models.IntegerField(default=0)),
                ('number_of_questions_answered', models.IntegerField(default=0)),
                ('number_of_questions_not_answered', models.IntegerField(default=0)),
                ('number_of_questions_skipped', models.IntegerField(default=0)),
                ('number_of_questions_not_attempted', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panel_candidates', to='authentication.candidate')),
                ('interview_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panel_candidates', to='interviewpanel.interviewpanel')),
            ],
            options={
                'verbose_name': 'Interview Panel Candidate',
                'verbose_name_plural': 'Interview Panel Candidates',
                'db_table': 'interview_panel_candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPanelQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_interview_panel_questions', to=settings.AUTH_USER_MODEL)),
                ('interview_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panel_questions', to='interviewpanel.interviewpanel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panel_questions', to='questionbank.question')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_interview_panel_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Panel Question',
                'verbose_name_plural': 'Interview Panel Questions',
                'db_table': 'interview_panel_questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPanelQuestionDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('number_of_hard_questions', models.IntegerField(default=0)),
                ('number_of_medium_questions', models.IntegerField(default=0)),
                ('number_of_easy_questions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panel_question_distributions', to='questionbank.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_interview_panel_question_distributions', to=settings.AUTH_USER_MODEL)),
                ('interview_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panel_question_distributions', to='interviewpanel.interviewpanel')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panel_question_distributions', to='questionbank.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panel_question_distributions', to='questionbank.topic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_interview_panel_question_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Panel Question Distribution',
                'verbose_name_plural': 'Interview Panel Question Distributions',
                'db_table': 'interview_panel_question_distributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
