# Generated by Django 5.2.8 on 2025-12-02 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewpanel', '20251203000000_add_report_pdf_path_and_cumulative_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReportAnswerwiseFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_session_answerwise_feedbacks', to='interviewpanel.interviewanswer')),
                ('interview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_session_answerwise_feedbacks', to='interviewpanel.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Session Answerwise Feedback',
                'verbose_name_plural': 'Interview Session Answerwise Feedbacks',
                'db_table': 'interview_session_answerwise_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
