# Generated by Django 5.2.8 on 2025-12-02 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewpanel', '20251130134149_0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_question_index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_panel_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_session', to='interviewpanel.interviewpanelcandidate')),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('skipped', 'Skipped'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('time_taken_in_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_answers', to='interviewpanel.interviewpanelquestion')),
                ('interview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviewpanel.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Answer',
                'verbose_name_plural': 'Interview Answers',
                'db_table': 'interview_answers',
                'ordering': ['created_at'],
                'unique_together': {('interview_session', 'question')},
            },
        ),
    ]
