# Generated by Django 5.2.8 on 2025-12-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewpanel', '20251202140633_20251130134150_interviewsession_interviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='analysis_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='full_transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='keywords_coverage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='keywords_matched',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='next_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='red_flags_detected',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_adaptability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_attention_to_detail',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_communication',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_creativity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_domain_knowledge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_problem_solving',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_stress_management',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_technical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score_time_management',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='current_difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='greeting_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='questions_asked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_questions_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_answers', to='interviewpanel.interviewpanelquestion'),
        ),
        migrations.AlterField(
            model_name='interviewanswer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('skipped', 'Skipped'), ('timeout', 'Timeout'), ('analyzing', 'Analyzing')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='interview_panel_candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_session', to='interviewpanel.interviewpanelcandidate'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('greeting', 'Greeting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='pending', max_length=20),
        ),
    ]
