# Generated by Django 5.2.8 on 2025-11-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '20251129091905_0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='organization',
        ),
    ]
