# Generated by Django 5.2.8 on 2025-11-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '20251129072608_20251128214643_candidate_organization_user_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='token',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='token_expires_at',
        ),
    ]
